### ISSUE TITLE
How do i use this mod?

### ISSUE THREAD

**Issue by Helloausername** [TechStudent10/CreationRotation#2]
theres 0 information on how to use it

**Comment by rubiidev18alt** [comment]
not op but:
1: after installing the mod, go to your levels.
2: press this button
![Screenshot_20241019_234135_Geode](https://github.com/user-attachments/assets/5919a756-7a59-4453-a83f-f19ad2124963)
3: select create lobby or join lobby
3.1: if you create a lobby, type the lobby code into somewhere popular like the gd discord
3.2: if you join a lobby, type in a id from somewhere, then press "join lobby"

**Comment by TechStudent10** [comment]
thank you for the explanation

I will be adding it somewhere in the about.md in the next update

**Comment by TechStudent10** [comment]
it's now in the about.md
