### ISSUE TITLE
It's crashing

### ISSUE THREAD

**Issue by Sans1ink** [TechStudent10/CreationRotation#4]
Ok ween I go in it it crashis soooo idk how to fix sooooon yeah tyvm

**Comment by TechStudent10** [comment]
hi, if the game itself is crashing can you please send a crashlog?
otherwise, can you send the error that the game gives you? thanks

**Comment by LumerGD120** [comment]
> hi, if the game itself is crashing can you please send a crashlog? otherwise, can you send the error that the game gives you? thanks

I experienced a crash while opening the join lobby tab like this:

https://github.com/user-attachments/assets/616b1a56-5009-4ccd-a9bd-b859c673d7ec

Also i have the crashlog right here

[Crash 2024-10-28 20.05.45.dmp](https://github.com/user-attachments/files/17542117/Crash.2024-10-28.20.05.45.dmp)

**Comment by TechStudent10** [comment]
please try the latest version, I believe I have fixed most crashes so far
